### ISSUE TITLE
.set / .setKey creates key with empty (not "not set") value

### ISSUE THREAD

**Issue by OddMorning** [MikeKovarik/rage-edit#11]
`.set`/`.setKey` creates new key with empty (not undefined value), i.e.

```js
await Registry.set('HKLM/Software/whatever')
await Registry.get('HKLM/Software/whatever') // Expected to be 'undefined' but it's an empty string
```

This is how `reg.exe add` works but I'm not really sure if it's a logical behavior. `setKey` sounds like it should set just key and nothing else. Besides that it's still possible to set undefined values via `.reg` files:

* Some_file.reg
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\test\undefined]

[HKEY_LOCAL_MACHINE\SOFTWARE\test\empty]
@=""
```

* JS
```js
await Registry.getValue('HKLM/Software/test/undefined') // undefined
await Registry.getValue('HKLM/Software/test/empty')     // ''
```

A possible solution to delete default value right after key creation in [set.mjs](https://github.com/MikeKovarik/rage-edit/blob/9371bf5399167d283def23961e565a97771dff7f/src/set.mjs#L28):

```js
Registry.setKey = async function(path) {
	<...>
	await execute(['add', path, '/f'])
	await execute(['delete', path, '/ve', '/f'])
}
```

If all of that makes sense not just for me, I could make a pull request.

**Comment by MikeKovarik** [comment]
It's been a while since I implemented it but as far as I remember, reg.exe always creates the empty string and it cannot be avoided (I could be wrong, there might be some argument that does this). I didn't make much of it but now since you put it that way it makes sense to create undefined value. You're welcome to submit PR.

**Comment by OddMorning** [comment]
I've tried different arguments in different order (just in case), but sadly nothing of that gave me the desired result. So it seems deleting `(default)` name manually is the only way to do that.
