### ISSUE TITLE
_replaceSpawn hook inaccessible 

### ISSUE THREAD

**Issue by ryunp** [MikeKovarik/rage-edit#13]
Commit  d3eb826d3cc1080b001849807377b0a6ec1855ed ('made the error message locale fetch automatic') removed **_replaceProcessSpawner** from the aggregated exportation. The updated **_replaceSpawn** function was never re-exposed.

**Comment by MikeKovarik** [comment]
That's correct. It was accidentally removed in that commit because it's undocumented internal api not covered by tests. And yes we changed it along with a few more breaking changes for the next major version we're working on with @OddMorning .

For now I'd recommend downgrading to 1.1.0
