### ISSUE TITLE
Hex/binary support

### ISSUE THREAD

**Issue by gautejohan** [MikeKovarik/rage-edit#14]
Hi,

thank you for a great util!

Is it possible to write hex/binary to a key, but keep the type as "REG_MULTI_SZ"?

I'm trying to write to ```HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations``` which is a  multi-string. The only problem is that I want my second array/string to be blank, but MULTI_SZ doesn't support this.

It works if you edit the key as binary (in regedit) and adds 0000 to the end, but I don't see how I can do this programatically.

Thanks for any input

**Comment by MikeKovarik** [comment]
Hi. I'm glad you like it.

I don't think that's possible. Under the hood we're executing reg.exe with a few arguments and this is what using REG_MULTI_SZ looks like. null terminated string sequence.
``` js
REG ADD HKLM\Software\MyCo /v MRU /t REG_MULTI_SZ /d fax\0mail\0\0
```

**Comment by OddMorning** [comment]
No, that's not possible. At least not with `reg.exe` which is used internally by this package.

Regedit says that "Data of type REG_MULTI_SZ cannot contain empty strings" when you try to add an empty string (but it says nothing when editing binary data which is quite strange).

For the same reason @MikeKovarik's example won't work:
```js
// '\0' is a line separator used by registry itself
let data = 'Item1\0Item2\0\0'
Registry.set(path, name, data, 'MULTI_SZ')
// Throws an error because reg.exe expected some data between '\0\0'
```

I tried to write raw bytes but `reg.exe` just cuts off everything after a `0` byte:
```js
// Works fine:
data = Buffer.from('\u0001\u0002\u0003\u0004')
Registry.set(path, name, data, 'MULTI_SZ')
// Binary value in registry: 01 00   02 00   03 00   04 00      00 00 00 00 00

// Doesn't work fine:
data = Buffer.from('\u0001\u0002\u0000\u0003\u0004')
Registry.set(path, name, data, 'MULTI_SZ')
// Binary value in registry: 01 00   02 00      00 00 00 00 00
```

---

Not elegant but working solution that I can think of is generate some `.reg` file with the following content:
```ini
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager]
"PendingFileRenameOperations"=hex(7):<...>
```
(`<...>` is a list of hex values separated by commas, e.g.: `5C,00,3F,00`)

and then import it with `child_process.spawn('reg.exe', ['import', 'temp_file.reg'])`

**Comment by gautejohan** [comment]
Thank you so much!

Yes, I could solve it with a reg file, but ended up using the RunOnce key instead (https://docs.microsoft.com/en-us/windows/desktop/SetupApi/run-and-runonce-registry-keys), then I can use rage as-is. 👍
