### ISSUE TITLE
Throws on Windows locales other than English

### ISSUE THREAD

**Issue by Eugeny** [MikeKovarik/rage-edit#4]
Non-existing registry keys throw errors when the error message doesn't match the English one. A possible fix is to detect the language-specific message by explicitly querying a non-existing key when the library starts.

**Comment by MikeKovarik** [comment]
It never occurred to me that cmd utilities might be translated to other languages. Comparing strings to find out about the error is not ideal to begin with but a necessary evil. Jumbling with various languages is not something I'd like to do but I guess there's no way around it. I'm just not sure when will I have the time for fixing it

**Comment by Eugeny** [comment]
I'll try to add a proper check sometime soon. Unfortunately, I had to fork and replace exceptions with returning undefined (`rage-edit-tmp` on NPM in case anyone needs this). It's a shame because rage-edit is currently the single best Promise-based registry lib out there

**Comment by MikeKovarik** [comment]
Glad to hear it. I'd be happy to accept PR as a minor version in a short term. And I'll try to think of a better way of handling errors later, perhaps as a major version, when i have some more time to dedicate to it.

**Comment by MikeKovarik** [comment]
I'm sorry it took so long. Couldn't find enough time throughout the week. I merged your code and ended up making it do the check automatically. I'd rather have the startup a second slower rather than causing headaches :D

**Comment by Eugeny** [comment]
Neat - would you let me know once it's released?

**Comment by MikeKovarik** [comment]
just did half an hour ago. 1.2.0
