### ISSUE TITLE
Abitlity to subscribe to registry key updates

### ISSUE THREAD

**Issue by caesar** [MikeKovarik/rage-edit#5]
It would be really useful to be able to subscribe to key updates.
I'm not sure if this is possible vie `reg.exe`? The win32 API is [`RegNotifyChangeKeyValue`](https://docs.microsoft.com/en-us/windows/desktop/api/Winreg/nf-winreg-regnotifychangekeyvalue).

Example use case: detecting when the Windows dark mode setting is toggled.

**Comment by MikeKovarik** [comment]
I would love to but unfortunately this is not possible with `reg`

**Comment by caesar** [comment]
Yeah, that's what I assumed. Oh well.

It would be a big project, but have you thought about implementing a native addon which accesses the registry directly instead of using `reg.exe`? It would also be more performant and I believe it avoids some security restrictions which can apply to access to `reg`. (Github's `registry-js` does this, but in my experience is rather buggy.)
