### ISSUE TITLE
Option to get access to 64bit registry from 32bit app

### ISSUE THREAD

**Issue by OddMorning** [MikeKovarik/rage-edit#7]
According to [this stackoverflow answer](https://stackoverflow.com/a/51594448), `reg.exe` allows to get access to particular "mode" of registry by specifying `/reg:32` or `/reg:64` argument (e.g. `REG QUERY HKLM\SOFTWARE /reg:64`). And it works (at least on Win7 x64 and Win10 x64).

It would be really useful if `rage-edit` supported such feature by specifying some option like:
```js
const path = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall'
const uninstall64 = await Registry.get(path, { mode: '64bit' })
const uninstall32 = await Registry.get(path, { mode: '32bit' })
```
The code above could help to get access to particular registry keys regardless of node.js type  
(there's no workaround because both `HKLM\Software\...` and `HKLM\Software\Wow6432Node\...` point to same place if node is 32bit)

**Comment by MikeKovarik** [comment]
Nice find. I didn't know about that. I'd like to get that implemented though I can't tell any date. I don't have any free time these days. It'd greatly help me if you could write some tests and tell something about it in readme. Btw I like the proposed `{mode}`, I'd go with that.

**Comment by OddMorning** [comment]
I'm not really sure if I did things the right way (it's always hard to read and understand someone else's code) but I hope it still can help you.  
Though I'm not sure if I composed tests the right way: `.hasKey`/`.hasValue` sections use `Registry.delete` which is get tested right in the next section.

**Comment by MikeKovarik** [comment]
Nice job. I feel you, I'm unsure about contributing too.

Regarding the tests, you're right, it's tricky and the get, set and delete method's tests rely on each other which is not right but it's the lesser of two evils. Otherwise we'd have to call reg.exe ourselves in the tests which could lead to more unintentional errors and ruin the tests. The way the tests are written I focus on one method at a time with `mocha test --grep="get()"` until it's green.

I only had time to glance over your commit and it's looking good but unfortunately I won't get to do anything for at least another week or so.

Also i had an idea. How about we enable autodetection (aka `{mode: 'auto'}`) by default which would set `64b` if the key path includes `WOW6432Node`. What do you think?

**Comment by OddMorning** [comment]
I afraid I don't really understand the idea. `WOW6432Node` contains keys for 32b apps, and you suggest to redirect 32b key paths keys to 64b paths?

In my head `{mode}` could work the following way and (in my opinion) it covers all the cases I can think of:

* Windows 64bit
  * Node 64bit  
     ```
      no mode:  HKLM\SOFTWARE =============> HKLM\SOFTWARE
      no mode:  HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE\WOW6432Node

      64bit:    HKLM\SOFTWARE =============> HKLM\SOFTWARE
      64bit:    HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE\WOW6432Node

      32bit:    HKLM\SOFTWARE =============> HKLM\SOFTWARE\WOW6432Node
      32bit:    HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE\WOW6432Node
    ```
  * Node 32bit  
     ```
      no mode:  HKLM\SOFTWARE =============> HKLM\SOFTWARE\WOW6432Node
      no mode:  HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE\WOW6432Node

      64bit:    HKLM\SOFTWARE =============> HKLM\SOFTWARE
      64bit:    HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE\WOW6432Node

      32bit:    HKLM\SOFTWARE =============> HKLM\SOFTWARE\WOW6432Node
      32bit:    HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE\WOW6432Node
    ```

* Windows 32bit
  * Node 32bit  
     ```
      no mode:  HKLM\SOFTWARE =============> HKLM\SOFTWARE
      no mode:  HKLM\SOFTWARE\WOW6432Node => ???
                  (TBH I don't know how Win32b reacts to such keys)

      64bit:    HKLM\SOFTWARE =============> null
      64bit:    HKLM\SOFTWARE\WOW6432Node => null
                  (ALWAYS return null / false / empty arrays / empty objects
                   in 64bit mode for better compatibility?)

      32bit:    HKLM\SOFTWARE =============> HKLM\SOFTWARE
      32bit:    HKLM\SOFTWARE\WOW6432Node => HKLM\SOFTWARE
    ```
